version: "3"

services:
    database:
        image: mariadb
        container_name: aos_mysql
        ports:
            - "3306:3306"
        volumes:
            - ./.docker/:/var/lib/mysql:rw
            - ./scripts:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vehiculos
            #MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_HOST: 172.25.0.2
 
        restart: on-failure
        networks:
            hostnet:
                ipv4_address: 172.25.0.2

    backend:
        image: omarpp/aos_vehiculos
        ports:
            - "8000:8001"
        volumes:
            - ./python:/code
        environment:
            PMA_HOST: database
            PMA_PORT: 3306
        depends_on:
            - database
        networks:
            hostnet:
                ipv4_address: 172.25.0.3
networks:
 #   driver: bridge
    hostnet:
        ipam:
            config:
                - subnet: 172.25.0.0/29


  