apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: omarpp/aos_vehiculos
          env:
            - name: PMA_HOST
              value: database
            - name: PMA_PORT
              value: "3306"
          volumeMounts:
            - name: python-code
              mountPath: /code
          ports:
            - containerPort: 8001
      volumes:
        - name: python-code
          hostPath:
            path: ../python/  # Reemplaza '/path/to/host' con la ruta en el host al directorio python
